from flask import Flask, render_template_string

app = Flask(__name__)

@app.route('/')
def home():
    html_content = '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My Web Page</title>
        <style>
            body { font-family: Arial, sans-serif; }
            h1 { color: blue; }
            .button {
  background-color: #04AA6D;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
   cursor: url('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d1a0243c-0d2e-4f82-bece-7f97b1c2e18b/dbl13kd-7d19cbaa-fa38-4f77-bfdb-667493806814.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2QxYTAyNDNjLTBkMmUtNGY4Mi1iZWNlLTdmOTdiMWMyZTE4YlwvZGJsMTNrZC03ZDE5Y2JhYS1mYTM4LTRmNzctYmZkYi02Njc0OTM4MDY4MTQuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.p5xJXcTP3-903iZo4G6UyCSYDliFKRmTVktsLy8DQF4'), pointer;
}
 body {
            cursor: url('https://www.rw-designer.com/cursor-view/133032.png'), auto; /* Fallback to default cursor */
        }
        </style>
    </head>
    <body>
        <h1>Hover over this area to see the custom cursor!</h1>
        <p>This is a simple web page generated by Python.</p>
        <button class="button">Go Fuck Yourself =)</button>
        <p> poop butt farts a bunch of dumb shit to see if the mouse acts normal on the page after it passes by the area of the button </p>
    </body>
    </html>
    '''
    return render_template_string(html_content)

if __name__ == '__main__':
    app.run(debug=True)
